classdef AssumptionPara
    properties
        idr
        iqr
        Ib
        P
        pu
        rou
        MaxLd
        CalLd
        CalRatedT
        CalMinT
        RatedSpeed
        MaxSpeed
        ismax
        delta
        PowerFactor
        ulim
        MaxSpeedid
        MaxSpeediq
    end
end